typography_spectrum: 0.06543606938794255
color:
  brandStrength: 0.940647846320644
  lightness: 0.8168870599474758
  saturation: 0.5920668495818973
  rhythmicContrast: 0.9993714687880129
  brandColors:
    - '#FFFFFF'
    - '#999A94'
    - '#6C7C89'
    - '#57503E'
    - '#A96C6C'
layout_spectrum: 0.8846352396067232
author:
  name: Lawry Boyer
  email: lmboyer04@gmail.com
name: Lawry Boyer
navigation:
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/lawryboyer'
    type: external
  - name: Pinterest
    url: 'https://www.pinterest.com/lawryboyer/'
    type: external
title: Architecture
description: What does a house want to be?
