typography_spectrum: 0.7208018184173852
color:
  brandStrength: 0.16786120319738984
  lightness: 0.5033402317203581
  saturation: 0.02145739202387631
  rhythmicContrast: 0.9515250525437295
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.48140933527611196
author:
  name: Lawry Boyer
  email: lmboyer04@gmail.com
name: Lawry Boyer
navigation:
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/lawryboyer'
    type: external
  - name: Pinterest
    url: 'https://www.pinterest.com/lawryboyer/'
    type: external
title: Architecture
description: What does a house want to be?
